### ISSUE TITLE
Explain setup

### ISSUE THREAD

**Issue by nschejtman** [beeftornado/duplicate-image-finder#1]
If you would be so kind to explain how to install the required packages would be great

**Comment by theconsultant** [comment]
Seconded, please and thank you ;-)

**Comment by JOJ0** [comment]
Hi, I am also struggling with setup at the moment. Somehow I don't get how to use setup.py. 
So I just tried to install all the necessary modules/packages app.py is asking for by hand using "pip install ..." 
Now when I run app.py it tells me this:

```
joj0@box:~/git/duplicate-image-finder$ duplicateimagefinder/app.py
Traceback (most recent call last):
  File "duplicateimagefinder/app.py", line 14, in <module>
    from output_formats import outputter_for_format
  File "/Users/jojo/git/duplicate-image-finder/duplicateimagefinder/output_formats/__init__.py", line 1, in <module>
    from duplicateimagefinder.enums import *
ImportError: No module named duplicateimagefinder.enums
```

Probably just a matter of app.py not finding something because of path issues or the like. Anyways, a short install.txt would be much appreciated!

Thanks and all the best
Jojo

**Comment by beeftornado** [comment]
Maybe `pip install -r requirements.txt` or `pip install -e .`

This should put `app.py` in your path so you can call it like `app.py ...`

**Comment by beeftornado** [comment]
Fixed in https://github.com/beeftornado/duplicate-image-finder/commit/7a7f84e80d66f91197d2b5f04c2e087e663c7fd2

I just added install instructions that I verified from scratch just now.
