### ISSUE TITLE
Not importing enums.py library

### ISSUE THREAD

**Issue by caiopizzol** [beeftornado/duplicate-image-finder#5]
Hi there, for some reason the script is not importing the library enums.py located in folder **duplicateimagefinder**

```
Traceback (most recent call last):
  File "./app.py", line 14, in <module>
    from output_formats import outputter_for_format
  File "/Users/caiooliveira/dev/boticario/duplicate-image-finder/duplicateimagefinder/output_formats/__init__.py", line 1, in <module>
    from duplicateimagefinder.enums import Formats
ImportError: No module named **duplicateimagefinder.enums**
```

To solve it, I have moved enums.py into the folder **output_formats**

Nice job by the way :)

**Comment by beeftornado** [comment]
I just added install instructions to the readme that I verified just now from scratch. Thanks for pointing this out. It looks like I didn't write the most portable cli 3 years ago :P 
Glad you figured it out, I didn't really expect this tool would still work after so long.

Fixed in https://github.com/beeftornado/duplicate-image-finder/commit/7a7f84e80d66f91197d2b5f04c2e087e663c7fd2
